version: '3'
services:
  superset:
    build:
      context: .
      dockerfile: Dockerfile  # Specify the path to your custom Dockerfile
    ports:
      - "8085:8088"
    env_file:
      - .env
    command: "gunicorn -w 4 -k gevent -b 0.0.0.0:8088 'superset.app:create_app()'"
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py
      - ./image/logo.webp:/app/superset/static/assets/images/logo.webp
    depends_on:
      - redis
    networks:
      - superset-net
    environment:
      - FLASK_ENV=production
      - SUPERSET_ENV=production

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - superset-net

networks:
  superset-net:
    driver: bridge
